language: node_js
node_js:
- '0.12'
- '0.11'
env:
  matrix:
    secure: LMkp6UUE66+oAgPdY4yMx52/FkMnSIOcehBXioFulaD0+hcF6xgCLKHccIzFfJ936KB49wTc9N05r6+ITXwRwkb6/vNadCgWnEgeFN7uSX9mejmuJKYcHmMVxjZZzYQE4ixPpD1XIg3w+SKb2MYZ9ZeVSnHzoeAceM8E2KW8sOKjLlZlSYHeUPtLIkpUsWJgOl7nyq42yyOYxtBVgrxCclOewKQNwvWLBAaS2KqZ9Tu1/YNsjWK2oMa/Hjl21L//4Ab3I8orbmqBBF2JxcCyyj5s3b1brCnHMwT5PU3Euf0jnk2Z+YmllG6bLZB09zY5Ls8glnO63R6BgNirBlBQbZ85KaJ/ZZyLteyEOWjhqGIjIGWTcMcMGWUy/Vd0THnObIE9SPT0A3KhWfD5IgneqvpAjsvHTlkf78foJ9IC7iSSGDXavYc7dNAz6aSq6goeUHV7G9fRo9d54t7Dv8wsnGlL/b0N+5EOD+Z3H9vjM4FVuUp9akVT89vkyecA30H0eGKAnSSZfg2U10BMt8MPBs21z7J/1sTOmJIQ14/dW6E7rzM8KTA6DdxHRfo66zSzAKkLrGWkezkNJKV3ggBGhtuAYKp8pnkmkjHtwqbqdwAFOb19eDvRLAV+tEDqbDyYaqpYRjKGVYnRZpgibY/1EU7ZtooH5qiqYMLteNk3mvU=
